version: '3'
services:
  web:
    build:  .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=V6SBxaZHZ4fvbHvVw1rbc97RXW8QnHZ2
      - POSTGRES_DB=db_api_oxqg
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: